// Verbatim objection rebuttal library ported from the standalone Sales
// Script tool's OBJ data object. Keyed by objection-category id (e.g.
// "mp_intro"), each feeding the slide-in Objections panel a script section's
// "Objections" button opens (see showObj in the standalone tool). Script
// copy is byte-for-byte identical to the source — do not edit the text.

export type Objection = { q: string; a: string };
export type ObjectionCategory = { title: string; sub: string; items: Objection[] };

export const OBJ: Record<string, ObjectionCategory> = {
  int_open:{title:"Opening Objections",sub:"Interview -- Step 1",items:[
    {q:'"I already have a job / I\'m not really looking."',a:'"I hear you -- and honestly that\'s usually who does best here. People who have something to walk away from. I\'m not asking you to quit anything today. I just want to see if what we\'re building is worth a real conversation. Can you give me 20 minutes?"'},
    {q:'"Is this insurance sales? I\'ve heard it\'s a pyramid scheme."',a:'"I get that completely -- and I would push back on the same thing. A pyramid scheme takes your money. This takes your time. There is no buy-in, no kit, no fee. You get licensed through a state exam, get contracted with carriers, and get paid every time you place a policy. That\'s a sales career -- not a scheme."'},
    {q:'"I\'m not sure I\'m cut out for sales."',a:'"That\'s actually the most honest thing you could say -- and it tells me you have self-awareness, which most salespeople don\'t have. The best agents I\'ve seen didn\'t come in thinking they were born salespeople. They came in coachable. Are you coachable?"'},
    {q:'"Can you just email me the information?"',a:'"I could -- but it wouldn\'t give you an accurate picture. The way our opportunity works is something that reads completely flat in an email. I\'d rather spend 20 minutes with you now and let you make an informed decision. If it\'s not a fit, I\'ll tell you myself."'}
  ]},
  int_disc:{title:"Discovery Objections",sub:"Interview -- Step 2",items:[
    {q:'"I don\'t have any sales experience."',a:'"Good -- that means you don\'t have any bad habits either. I can teach sales. What I cannot teach is work ethic, coachability, or the hunger to build something. Do you have those?"'},
    {q:'"I need something stable right now."',a:'"I understand -- and I want to be straight with you. If you need a guaranteed paycheck to keep the lights on starting next week, this probably isn\'t the right timing. But this is the most stable long-term income you can build -- because you own the book and no one can lay you off. It takes 60 to 90 days to build that foundation. Is that timing workable?"'},
    {q:'"I\'ve tried commission before and it didn\'t work out."',a:'"Tell me more -- because there is a big difference between a bad commission structure and a bad environment. What was the product? What did support look like? What I\'m offering is leads, training, mentorship, and a structure that works. What was different about that last experience?"'},
    {q:'"I\'m not a phone person."',a:'"Most of the best closers I know said the exact same thing. The phone is a skill, not a personality type. With warm leads -- people who asked to be called -- it stops feeling like selling about 2 weeks in and starts feeling like helping. That shift is real."'}
  ]},
  int_role:{title:"Role Objections",sub:"Interview -- Step 3",items:[
    {q:'"8 to 10 hours a day sounds like a lot."',a:'"It is -- and I\'m not going to pretend it isn\'t. But consider what you\'re building. Most people work 8 to 10 hours a day at a job that caps their income and fires them when it\'s convenient. Here, those hours go directly into your own business. The agents who put in that time in the first 90 days are working 4 to 5 hours a day six months later -- because they built the leverage."'},
    {q:'"What does a typical day actually look like?"',a:'"Wake up, check your pipeline. You block off calling hours -- most agents do 9 to 12 and then 1 to 4. You work your leads, run presentations, follow up on pending applications, submit new business. The structure is yours to build, but the discipline has to come from you."'},
    {q:'"Is this full-time or part-time?"',a:'"It can technically be either -- but I will be honest. The agents who treat this part-time get part-time results. The agents who go all in in the first 90 days create full-time income fast. What I recommend is giving it 90 days of full effort and letting the results tell you what it\'s worth."'},
    {q:'"I don\'t have a quiet place to work from home."',a:'"That\'s something we can problem-solve -- a car, a library, a quiet room during specific hours. The logistics are always solvable. The bigger question is the willingness. Where there\'s a will on that stuff, we always find a way."'}
  ]},
  int_comp:{title:"Compensation Objections",sub:"Interview -- Step 4",items:[
    {q:'"I can\'t survive on commission only."',a:'"I hear you -- and I\'m not going to pretend the first 30 to 60 days aren\'t an adjustment. Do you have a bridge -- savings, a part-time income, a partner\'s income -- to get through the ramp? Because on the other side of that ramp, there is no ceiling. The agents who get through the first 90 days almost never go back to a salary."'},
    {q:'"What is the average income for new agents?"',a:'"Honest answer -- it depends entirely on effort and coachability. Agents who work consistent hours and follow the process in their first year are making $80,000 to $120,000. Agents who treat it like a side hustle make side hustle money. I can give you the tools, the leads, and the training -- but the income is yours to build."'},
    {q:'"A chargeback sounds scary."',a:'"It sounds scary and I\'m glad I told you about it -- because most people in recruiting skip right over it. The protection against chargebacks is simple: write quality business. Put the right person in the right product for the right reason. Do that consistently and chargebacks become a non-event."'},
    {q:'"Why 1099 and not W2?"',a:'"Because you are running your own business. 1099 means you own the upside -- your tax deductions, your schedule, your book, your renewals. W2 means the company owns the client relationship. The trade-off for carrying your own expenses is that everything you build is yours. That\'s the deal."'},
    {q:'"What does the carrier spread mean for me practically?"',a:'"It means before you submit a case, you check the comp grid for that specific carrier and product. We walk you through this in training. It\'s not complicated -- it\'s just knowing your numbers before you dial, not after. The agents who know their comp never get surprised."'}
  ]},
  int_leads:{title:"Leads and Expense Objections",sub:"Interview -- Step 5",items:[
    {q:'"So I have to pay for my own leads after 6 weeks?"',a:'"Yes -- and here\'s the context. You own your book from day one. Every client, every renewal, every referral is yours permanently. The trade-off for that ownership is that you carry your own overhead. Most agents cover their lead cost on their first or second close of the month."'},
    {q:'"What do leads actually cost?"',a:'"It varies by product and vendor -- but most agents are spending a few hundred to a few thousand a month depending on their volume. We walk you through what other agents at your level are spending so there are no surprises. The math always works -- because the commission on one policy covers the cost of the leads that generated it."'},
    {q:'"What if I don\'t close anything in the first 6 weeks?"',a:'"Then we need to have an honest conversation about why. Most agents are placing their first policy within the first 2 to 3 weeks. If someone is not closing in 6 weeks, it\'s almost always a skill gap -- and skill gaps are fixable with coaching. The leads work. The product works. We just have to figure out where in the process something is breaking down."'},
    {q:'"What happens to my book if I leave?"',a:'"It stays yours. Your renewals, your clients, your relationships -- those belong to you regardless of what happens with our working relationship. That is the biggest difference between us and most agencies."'}
  ]},
  int_growth:{title:"Growth and Leadership Objections",sub:"Interview -- Step 6",items:[
    {q:'"How long does it take to move up?"',a:'"That\'s entirely up to you -- and I mean that literally. Agents who hit consistent production in 60 to 90 days and want to start building a team can step into a training role inside their first 6 months. There is no time-in-grade requirement. It\'s based on what you produce."'},
    {q:'"What are overrides exactly?"',a:'"An override is a percentage of the commission on every policy your team writes. So if you bring on an agent and mentor them, and they place a $1,000 commission policy, you receive an override on top of that -- without placing the policy yourself. That\'s passive income. That\'s leverage. And it compounds as your team grows."'},
    {q:'"Is there pressure to recruit instead of sell?"',a:'"No -- and I want to be clear about that. You never have to recruit to make great money here. Recruiting is an option that opens a second income stream -- not a requirement. Plenty of our top earners are individual agents who just sell. Both paths are respected."'},
    {q:'"What if I want to build my own brand eventually?"',a:'"That\'s exactly what we\'re set up for. The agency-builder track inside Tier 1 is designed for agents who want to eventually put their name on something. You build your team, develop your culture, and run your agency -- all inside the infrastructure we provide."'}
  ]},
  int_products:{title:"Product Objections",sub:"Interview -- Step 7",items:[
    {q:'"I don\'t feel comfortable selling insurance to veterans."',a:'"I understand that instinct -- but let me reframe it. You are not selling to veterans. You are responding to veterans who asked for help. They submitted a form because they\'re worried about leaving a burden on their family. Your job is to show up, explain their options honestly, and get them covered. That\'s service, not a sale."'},
    {q:'"What if someone can\'t afford it?"',a:'"Then you tell them the truth and move on. Not every lead becomes a policy -- and that\'s okay. Your job is not to force someone into a product they can\'t afford. It\'s to find the people who can, and match them with the right product. The market is massive."'},
    {q:'"Is final expense a hard sell?"',a:'"It\'s actually the opposite. When someone has already told you they\'re worried about their funeral costs, the conversation is not about convincing them they need it. It\'s about figuring out what they qualify for and what they can afford. The need is already established. You\'re just solving it."'},
    {q:'"What makes our products better than what they can get online?"',a:'"Two things. First -- personalization. Online products are generic. We match the client to the right carrier based on their actual health profile. Second -- advocacy. When a claim happens, we\'re there. When a client has a question, they call us. You can\'t get that from a website."'}
  ]},
  int_close:{title:"Closing Objections",sub:"Interview -- Step 8",items:[
    {q:'"I need to think about it."',a:'"That\'s fair -- what specifically do you want to think about? If there\'s something I haven\'t explained clearly, I\'d rather address it now than have you sitting with a question I could just answer. What part of this feels unclear?"'},
    {q:'"I need to talk to my spouse or family."',a:'"Absolutely -- and I\'d expect that. Can I ask what their main concern is likely to be? I\'ve had this conversation with a lot of spouses and I can usually tell you right now how it goes. The most common concern is income security -- and we have a real answer for that."'},
    {q:'"I\'m worried about the licensing cost."',a:'"The exam cost is typically $150 to $200 and about a week or two of studying. Most agents earn that back on their first policy -- usually within the first two weeks of being licensed. It\'s the smallest financial commitment you\'ll ever make for something that can genuinely change your income trajectory."'},
    {q:'"I have another offer I\'m considering."',a:'"You should explore every option -- I mean that. All I would ask is that you compare them honestly. Compare the ceiling, compare who owns the clients, compare what happens to your income if you leave. If the other offer wins on those things, take it. But I suspect when you look at the long-term math, this is a different conversation."'},
    {q:'"Can I start part-time and see how it goes?"',a:'"You can -- but part-time effort tends to produce part-time income, and a lot of people who start part-time never build enough momentum to go full-time because they never break through the learning curve. The agents who commit fully for 90 days are the ones who have real data to make a decision. That\'s what I recommend."'}
  ]},

  fe_intro:{title:"Intro Objections",sub:"Final Expense -- Step 1",items:[
    {q:'"Where are you calling from?" / "Are you the VA?"',a:'"I manage the brokerage that handles all the veteran\'s final expense options."<br><br><em>Push back "Who is that?":</em> "I\'m an underwriter that helps go over your life options and eligibility."'},
    {q:'"I already have funeral coverage in place!"',a:'"Perfect, glad you have that taken care of. So you were planning on leaving some extra money behind for the loved ones, correct?"<br><br><em>Push back "I already have that covered as well":</em> "Got it, so a lot of veterans are looking to utilize their veterans discount. Did you get that through us or a private carrier? How much are you currently covered for? How long ago did you get that in place?"<br><br><em>IF 5+ years:</em> "Perfect, I\'m glad you got that when you were a little bit younger. Were you planning on using that for a burial or cremation?" Then spend their coverage -- overstate funeral costs and inflation, mortgage/debts, leftover bills.<br><br><em>IF less than 5 years:</em> "Let me make sure your veterans discount was applied. What do you pay on that each month?" See if you can beat the quote. If you can -- continue with script. If you can\'t -- spend their coverage.'},
    {q:'"You are the 10th person that has called me!"',a:'"I completely understand, but it doesn\'t look like anyone has contacted you for the Veterans Program. Do you currently have anything in place to help cover your funeral god forbid you passed away today?" Then go back to script.'},
    {q:'"I\'m not interested!"',a:'"Did you know what this was about? This is to cover your funeral expenses. Do you currently have anything in place to help cover your funeral god forbid you passed away today?" Then go back to script.'},
    {q:'"I don\'t remember filling this out!"',a:'"No worries, it does take us about a few weeks to get to your file. You put your date of birth as ___ correct? Most people\'s main concern is to make sure that their final expense doesn\'t fall a burden on their loved ones. Do you currently have anything in place?" Then go back to script.'},
    {q:'"This is not a good time / I\'m busy!"',a:'"I understand (client first name), however this is the only time slot we have available for you. But don\'t worry -- this will only take a few minutes." Then go back to script.'},
    {q:'"The VA will take care of my burial."',a:'"Of course, if you are planning on being buried in a national cemetery, the plot and headstone is covered. However that still leaves behind $8,000 to $10,000 that the family has to cover. Did you have anything to cover the rest of those expenses?" Then go back to script.'},
    {q:'"Looking for disability benefits, not insurance."',a:'"Absolutely, I can point you in the right direction with that once we get done. Do you currently have anything in place to help cover your funeral god forbid you passed away today?" Then go back to script.'}
  ]},
  fe_why:{title:"Dig Into Why Objections",sub:"Final Expense -- Step 2",items:[
    {q:'"My family will figure it out."',a:'"I completely respect that -- but can I be real with you for a second? Most families don\'t figure it out. They\'re grieving and suddenly staring at a $15,000 to $20,000 funeral bill with no plan. That combination is brutal. What you\'re doing today is making sure (beneficiary) has one less thing to carry at the worst moment of their life."'},
    {q:'"I have savings that can cover it."',a:'"Perfect -- how much do you have set aside specifically for final expenses? Because the average funeral today runs $15,000 to $20,000, and that doesn\'t include outstanding debts or bills left behind. If your savings can absorb all of that and still leave (beneficiary) financially stable -- great. But most veterans I talk to realize the savings are earmarked for other things."'},
    {q:'"I\'m on a fixed income -- I can\'t afford it."',a:'"I completely understand, and that\'s exactly why plans start at $40 to $50 a month. I\'m not here to stretch your budget. At the end of the month after all your bills are paid, is $40 something you could set aside to make sure (beneficiary) doesn\'t have to carry this?"'},
    {q:'"I\'m too old to get coverage."',a:'"That\'s actually one of the biggest myths in this space. Most of the plans we work with cover veterans up to age 85 and many have simplified or guaranteed issue -- no medical exam. Let me ask you a few quick health questions and I\'ll tell you exactly what you qualify for."'}
  ]},
  fe_suit:{title:"Suitability Objections",sub:"Final Expense -- Step 3",items:[
    {q:'"Why do you need to know my income?"',a:'"By law I\'m not allowed to show you options for more than 10% of your income. So it protects you -- I can\'t recommend something that would stretch your budget past what makes sense. What would you say you bring in per month, just a ballpark?"'},
    {q:'"Why do you need my medical history?"',a:'"The carriers use it to determine what you qualify for and at what rate. It\'s not up to me -- it\'s up to the carriers. And honestly, the more accurate the information, the better the options I can find for you. Everything you share stays between you, me, and the carrier."'},
    {q:'"I\'ve been declined before."',a:'"That happens more than you would think -- and it doesn\'t mean you\'re uninsurable. It means you may not have been matched with the right carrier. We work with 26 A-rated carriers. Some specialize in higher-risk health profiles. Let me ask you a few questions and I\'ll tell you honestly what I think we can find."'},
    {q:'"I don\'t want to go through all these questions."',a:'"I completely understand -- and I promise I\'ll make it as quick as possible. These questions are what allows the carriers to approve you. It\'s about 5 minutes and then we\'re done. Can we do 5 minutes together?"'}
  ]},
  fe_benefits:{title:"Benefits Presentation Objections",sub:"Final Expense -- Step 4",items:[
    {q:'"I need to see something in writing first."',a:'"Absolutely -- and you will. Once we get you approved I\'ll send over the full policy documents electronically and a physical copy arrives in the mail within 10 to 12 business days. What I need from you right now is just to confirm a few more details so I can get the application submitted."'},
    {q:'"I don\'t trust insurance companies."',a:'"That\'s fair -- and that\'s exactly why I sent you my license. I only work with A-rated carriers that have been in business for 50 to 100-plus years. These are not fly-by-night companies. And when something happens, they pay. That\'s what an A-rating means. Do you still have my license on your phone?"'},
    {q:'"What is the two-year waiting period you mentioned?"',a:'"Great question -- and the reason I highlighted immediate coverage is specifically because we do not have that on these plans. Our plans cover you from day one, dollar one. That\'s one of the biggest advantages of what we offer."'},
    {q:'"What happens if I miss a payment?"',a:'"Most carriers have a 30-day grace period. The policy doesn\'t lapse immediately -- you have 30 days to make it right. And if something happens during that grace period, the carrier still pays the claim minus whatever premium was owed. Your coverage doesn\'t disappear the moment a payment is late."'}
  ]},
  fe_numbers:{title:"Numbers Objections",sub:"Final Expense -- Step 5",items:[
    {q:'"I need to think about it -- make sure it\'s affordable!"',a:'"Of course. Did you want to think about which option you should go with<span class="pause">....</span> or if you felt like you needed this at all?<br><br>Which option: Do you mind if I make a recommendation? Most veterans in your position start with bare minimum -- make sure you can get the coverage and foot in the door and make sure (their need) is covered for (beneficiary\'s name). If later on you decide you want to go with the silver or gold option, we can always increase it. But the main thing today is to make sure you can get the coverage. Does that make sense?" -- proceed to application.<br><br>Don\'t need: spin back on why. Did they have any insurance? Any money saved up? If yes, is it enough? $10k isn\'t enough for burial -- most add $5k to factor in inflation. HARD CLOSE: Shove the why down their throat till they pick an option or hang up.'},
    {q:'"I need to talk to my wife about it!"',a:'"I completely understand<span class="pause">....</span> I\'m the same way, I talk to my wife about everything. She is the beneficiary of the plan -- she has to know what\'s going on. You can\'t keep this a secret. Do you need to talk to her about which option to go with<span class="pause">....</span> or if you need this at all?<br><br>Which option: Do you mind if I make a recommendation? Most veterans in your position start with bare minimum. Later when you talk to the wife, if you two decide to go with silver or gold, we can always increase it. But the main thing today is to make sure you can get the coverage. Does that make sense?<br><br>Push back 2: (client name), we can both agree that accidents can occur at any time, correct? If something happened to you while driving on the way home tomorrow<span class="pause">....</span> and you had put this protection in place for your wife -- do you think you would have regretted getting (beneficiary\'s name) covered? On the worst day of (beneficiary\'s name) life would you rather have her receive a check or have to write a check?"'},
    {q:'"I\'m just shopping around today!"',a:'"I completely understand -- I\'m the same exact way, I want to make sure I\'m not paying more than I need to for anything. The good news is<span class="pause">....</span> with the veterans program they do the shopping for you with all 26 partnered carriers in the country to get you the lowest rate. But of course our goal today is to make sure you can get the coverage. Which one option makes the most sense to you<span class="pause">....</span> BRONZE<span class="pause">....</span> SILVER<span class="pause">....</span> or GOLD?" -- proceed to application.'},
    {q:'"Can you send it in the mail?"',a:'"Absolutely -- you\'ll get everything in the mail in about a week. But coverage only activates once we set it up, so the sooner we do it, the sooner your family is protected. Which one option makes the most sense to you<span class="pause">....</span> BRONZE, SILVER, or GOLD?" -- proceed to application.'}
  ]},
  fe_social:{title:"SSN & Banking Objections",sub:"Final Expense -- Steps 6 & 7",items:[
    {q:'"Why do you need my Social Security number?"',a:'"It\'s just for the application<span class="pause">....</span> that\'s how they go over your medical history and make sure everything checks out. Does that make sense? Now go ahead with the social."'},
    {q:'"I don\'t feel comfortable giving my SSN over the phone."',a:'"I completely understand -- that\'s just how they go over your medical history and make sure you don\'t weigh 500 pounds or are like tied to a hospital bed. Does that make sense? Now go ahead with the social.<br><br>Push back 3: Most importantly that\'s the ONLY thing on your death certificate when you die for them to pay out your loved ones. Does that make sense? Now go ahead.<br><br>Push back 4: The carrier just has to verify the SSN on file so god forbid when the time comes your loved ones receive a check instead of giving out a check. Does that make sense? Now go ahead with your social.<br><br>Last resort: Send a pic of the application with the carrier name and their name. "Do you see your name there? And the name of the carrier on the screen? Got it -- so you were able to validate everything there right? Perfect, now go ahead with the social."<br><br>iPhone: Ask to hop on FaceTime to process the rest of the application for full transparency. Then ask for social.'},
    {q:'"I don\'t want to give my bank account number."',a:'"I completely understand -- now quick question (Client\'s Name): have you ever given or received a check from anyone in your lifetime? At the bottom of every check you\'ll see the same routing and account number because that information can\'t be used to buy something online. All this is doing is putting an electronic check on file. Does that make sense? Now go ahead with the account number."'},
    {q:'"I want something in writing first / I just want an approval now!"',a:'"I completely understand -- so the state is required by law to validate that the insured and payor of the policy is the same person before anything is submitted. Just for your safety and the safety of others. Does that make sense? Now go ahead with the account number."'},
    {q:'"Final pushback -- lack of trust:"',a:'"For full transparency here. Do you receive text messages to this phone? I\'m gonna send you a picture of my screen for further transparency.<br><br>[Send a pic of the application with carrier name and their name]<br><br>Do you see your name there? And the name of the carrier on the screen? Got it -- so you were able to validate everything there right? Perfect, now go ahead with the account number.<br><br>IF iPhone: Send text above. Ask to hop on FaceTime to process the rest of the application for full transparency. Then ask for account number."'}
  ]},
  fe_close:{title:"SSN & Banking Objections",sub:"Final Expense -- Steps 6 & 7",items:[
    {q:'"Why do you need my Social Security number?"',a:'"It\'s just for the application<span class="pause">....</span> that\'s how they go over your medical history and make sure everything checks out. Does that make sense? Now go ahead with the social."'},
    {q:'"I don\'t feel comfortable giving my SSN over the phone."',a:'"I completely understand -- that\'s just how they go over your medical history and make sure you don\'t weigh 500 pounds or are like tied to a hospital bed. Does that make sense? Now go ahead with the social.<br><br>Push back 3: Most importantly that\'s the ONLY thing on your death certificate when you die for them to pay out your loved ones. Does that make sense? Now go ahead.<br><br>Push back 4: The carrier just has to verify the SSN on file so god forbid when the time comes your loved ones receive a check instead of giving out a check. Does that make sense? Now go ahead with your social.<br><br>Last resort: Send a pic of the application with the carrier name and their name. "Do you see your name there? And the name of the carrier on the screen? Got it -- so you were able to validate everything there right? Perfect, now go ahead with the social."<br><br>iPhone: Ask to hop on FaceTime to process the rest of the application for full transparency. Then ask for social.'},
    {q:'"I don\'t want to give my bank account number."',a:'"I completely understand -- now quick question (Client\'s Name): have you ever given or received a check from anyone in your lifetime? At the bottom of every check you\'ll see the same routing and account number because that information can\'t be used to buy something online. All this is doing is putting an electronic check on file. Does that make sense? Now go ahead with the account number."'},
    {q:'"I want something in writing first / I just want an approval now!"',a:'"I completely understand -- so the state is required by law to validate that the insured and payor of the policy is the same person before anything is submitted. Just for your safety and the safety of others. Does that make sense? Now go ahead with the account number."'},
    {q:'"Final pushback -- lack of trust:"',a:'"For full transparency here. Do you receive text messages to this phone? I\'m gonna send you a picture of my screen for further transparency.<br><br>[Send a pic of the application with carrier name and their name]<br><br>Do you see your name there? And the name of the carrier on the screen? Got it -- so you were able to validate everything there right? Perfect, now go ahead with the account number.<br><br>IF iPhone: Send text above. Ask to hop on FaceTime to process the rest of the application for full transparency. Then ask for account number."'}
  ]},

  mp_intro:{title:"Intro Objections",sub:"Mortgage Protection -- Step 1",items:[
    {q:'"Where are you calling from?" / "Who do you work for?"',a:'"I\'m just the state\'s licensed medical underwriter that\'s been assigned to your file."<br><br><em>(back to script)</em>'},
    {q:'"If they hang up"',a:'"Hi ___, seems we got disconnected there." <em>(go back into script or repeat what they said before they hung up)</em>'},
    {q:'"Is this required?"',a:'"Oooof… I mean… technically they won\'t take your home away if you don\'t... uh but I will tell you… you\'d be one of the rare people not to put it in place since it\'s just such crucial coverage… It\'d be like driving a car without car insurance, if that makes sense." <em>*(act confused and a bit thrown off guard as to why they would even ask that)*</em>'},
    {q:'"Not Interested"',a:'"Understandably, most people aren\'t interested until they get cancer, disabled, or God forbid pass away -- anyway it looks like the address we have on file for the home is ____?<br><br><em>2nd time:</em> Hmm, well I\'m assuming what was on your mind when you submitted this request to our office was simply providing some sort of practical, affordable coverage to protect the home and your family God forbid when something does happen to you…?<br><br><em>3rd time:</em> Ok, well are you afraid the price is going to be too high or are you afraid you\'re going to be declined?<br><br><em>Declined:</em> Correct, I see that on your file here. I\'m the senior medical underwriter that\'s been assigned to figure out some options you will qualify for.<br><br><em>Price too high:</em> Correct, I see that on your file here -- looks like you were quoted some pretty high numbers by one of my sales reps. I\'m the manager that handles the ___(county/city)___ area that\'s been assigned to figure out some more practical, affordable options that make sense for your budget."'},
    {q:'"Take me off the list."',a:'"To be frank with you ___, there is no list -- I\'m sorry you may be confused, this is the request YOU submitted in regards to protecting your family God forbid you were to get cancer, disabled, or pass away. Anyway, it looks like the address we have on file for the home is ____?"'},
    {q:'"I can\'t afford it right now."',a:'"I completely understand -- I see on your file here you were quoted some pretty steep numbers by our sales rep, which is the reason for my call. I\'m the medical underwriter that has been assigned to figure out something more practical and affordable. Anyway, the address we have on file for the home is ____?"'},
    {q:'"I\'m busy right now. Can you call me back?" / "I\'m at work."',a:'"I\'m really busy as well and I have a lot of families to get to. I\'ll make this brief -- go ahead and grab something to write with so we can get this taken care of real quick."'},
    {q:'"I\'m driving."',a:'"I don\'t want you to get in an accident -- go ahead and pull over real quick, I\'ll get your information pulled up."'},
    {q:'"Are you with my bank?"',a:'"Yep, good question! ___(their lender)___ now handles the mortgage, refi, and equity side of things, and then after closing it\'s passed off to the mortgage protection department. It\'s always done right after closing and separately from the home, so that you\'re the beneficiary now and not the bank… does that make sense?"'},
    {q:'"I saw an ad." (accidental coverage confusion)',a:'"Yes, that is for accidental coverage so it only covers you if you were to die in an accident. Were you looking for accidental only or did you want something that would cover you for any cause of death?"'},
    {q:'"I already have coverage through work."',a:'"That\'s great that you have some through work -- but after you leave, retire, or change jobs all that coverage goes away. And worst case if you get cancer or some sort of illness and you end up getting laid off, you lose those benefits as well and then most likely you wouldn\'t be able to qualify health wise for any coverage. These are private policies and they\'re meant to be supplemented with private insurance. Anyway, it looks like the address we have on file for the home is ____?"'},
    {q:'"Now\'s not the right time."',a:'"Totally get it. These programs are based on age and health -- so waiting can actually increase the cost or limit your eligibility later. If we lock in a small amount of coverage now while you\'re in good health, that would be important to you, correct?"'},
    {q:'"I don\'t own that house anymore." / "We\'re going to sell the home."',a:'"Perfect -- this coverage actually sticks with you and transfers with you when you buy a new home. Do you plan on staying local or are you moving out of state?"<br><br><em>Already sold:</em> "Perfect -- did you purchase a new home or are you renting?"<br><br><em>Bought new home:</em> "Perfect, it looks like that\'s why your file was flagged here and coming up as incomplete… what\'s the new updated mortgage address? I\'ll update your file for you."<br><br><em>Now renting:</em> "Perfect, it looks like that\'s why your file was flagged here and coming up as incomplete… We also handle life insurance and protection that covers you if God forbid you were to become sick, disabled, or pass away. Have you guys gotten that set up yet?"'},
    {q:'"I don\'t really understand how it works."',a:'"Totally fair. Let me simplify it: mortgage protection is just a policy that\'s set up to pay off your home or help your family cover payments if something happens to you. You know how when the primary income earner unexpectedly passes away or gets disabled, and their loved ones are left without the income to keep up with the mortgage -- they ultimately end up losing the home and all the equity they have saved up in it? Well what we do is help people qualify for financial protection plans so they don\'t have to worry about that."'},
    {q:'"I don\'t remember requesting this."',a:'"Did maybe a spouse fill it out? Or a child? <em>(if no)</em> Do you currently have any protection for your family that pays out if you\'re sick, disabled, or pass away set up currently? Ok, well that\'s ok -- if you\'re anything like me I forgot what I had for breakfast. This will be quick, go ahead and grab a pen and paper and we can get this taken care of for you."'},
    {q:'"I\'ve had a bad experience with insurance."',a:'"Totally hear you -- some companies haven\'t always made it easy. What I can tell you is the carriers I work with are A-rated, with great reputations for paying claims. And I\'m here to walk with you through the process step-by-step, no pressure. Out of curiosity -- was the issue with the policy itself, or how it was explained or handled?"'},
    {q:'"I already have insurance." / "I already got this taken care of."',a:'"Perfect, that\'s the reason for my call -- I see that on your file here. To confirm I\'m speaking with the right person, it looks like the address we have on file for the policy is _______? Perfect, and looks like I have your Date of Birth listed on here as ___? Gotcha. Reason for my call is I\'m the supervisor following up because it looks like one of our junior underwriters helped you with coverage but did not update your file here…<br><br>Did you get the policy packet in the mail ok? Did you go with the complete plan or the partial plan? How much coverage? How much are you paying a month? Now which one of our companies did you end up going with? Is there a reason you went with one of our B-rated carriers? Could you not qualify for one of our top-rated ones? Any health issues at all?<br><br><em>*(look up quotes to see if you can get cheaper, OR build value on living benefits, cash value if it\'s a term, etc.)*</em><br><br>Ok, well this will only take a few minutes and we can get this switched for you. Looks like the mailing address we have on file for the policy is ______ ?"'},
    {q:'"I\'m confused -- I have homeowners insurance." (Allstate, Farmers, State Farm, AAA, etc.)',a:'"Has anyone explained the difference between homeowners insurance and mortgage protection with you before?"'},
    {q:'"We took care of that at closing."',a:'"Correct, you took care of your mortgage at closing -- but I\'m calling in regards to the mortgage protection. The banks used to offer this back before 2008 but now it\'s contracted out directly to the various insurance carriers, which is who I work with. It\'s my job as the underwriter licensed with the state to run it through the various companies to figure out which option and product makes the most sense for you and your family. Make sense?"'},
    {q:'"We don\'t have that lender anymore."',a:'"Correct, that\'s the reason for my call -- I see that on your file which is probably why it\'s still pending and slipped through the cracks on our end here, I apologize. To confirm I\'m speaking with the right person, the address we have on file here for the mortgage is ___(address)___? Gotcha -- so as you may recall this is the coverage that takes care of the home God forbid you become sick, disabled, or pass away. Make sense?"'},
    {q:'"Call me back later."',a:'"Totally get it -- don\'t want to catch you at a bad time. Just to see if it even makes sense for me to call you back later -- were you maybe looking for anything specific or just wanting to check out all the different options?"'}
  ]},
  mp_frame:{title:"Frame and Qualification Objections",sub:"Mortgage Protection -- Step 2",items:[
    {q:'"Why do you need my Social Security number?" / "I\'m not comfortable giving that out."',a:'"Understood, I hear ya (client\'s name). The insurance carrier requires that because that\'s how they\'re going to check your medical and prescription history, and it also prevents fraud so someone\'s not signing up for coverage in your name. Does that make sense? Okay cool -- confirm that social with me again?<br><br><em>If they give more pushback:</em> We actually have insurance that if anybody were able to get through all of our firewalls and access your info, it would cover you for up to a million dollars. That should be enough, right? <em>(wait for response)</em> Ok, go ahead with the social."'},
    {q:'"Why do you need my bank information?" / "I don\'t want to give that out."',a:'"The insurance carrier either requires a voided check or account number to verify there is no insurance fraud, money laundering, or anything else fraudulent linked to your account -- and of course that\'s also how you\'ll be paying for the policy once you\'re approved. Anyway, looks like the address we have on file to mail the policy out to is ___?<br><br><em>If they\'re still giving pushback:</em> I also just texted you a link to the Department of Insurance to look up my information and make sure I\'m legit. Let me know when you get the link. <em>(walk them through how to verify your license: https://sbs.naic.org/solar-external-lookup)</em>"'},
    {q:'"I already have PMI."',a:'"PMI protects the bank -- not you or your family. If something happens to you, PMI does not pay off your mortgage or keep your family in the home. It simply means the bank recovers their money. Mortgage protection is the coverage that actually works for your family. Those are two very different things."'},
    {q:'"Can\'t you just give me a quote without all the information?"',a:'"I can give you a ballpark -- but it wouldn\'t be accurate because rates are based on your age, health, and mortgage balance. The questions take about 2 minutes. Then the numbers I give you are actually your numbers."'}
  ]},
  mp_why:{title:"Building the Why Objections",sub:"Mortgage Protection -- Step 3",items:[
    {q:'"My spouse would just sell the house."',a:'"That might be the plan -- and the question is whether they would have the time and financial runway to sell it at full market value, or whether they\'d be forced to sell quickly at a discount just to cover the mortgage payments. This coverage buys them that time. Without it, they may be making a $50,000 decision under the worst possible emotional and financial pressure."'},
    {q:'"I have enough savings to cover it."',a:'"That\'s great -- and I want to make sure the math holds. The average mortgage balance is over $200,000. If that came due because of an unexpected death or disability, would your savings absorb that and still leave your family financially stable? For most people, the savings are earmarked for other things."'},
    {q:'"I\'m healthy -- I don\'t need to worry about this."',a:'"Being healthy is exactly why right now is the best time to lock this in. Rates are based on your health today. Every year that passes, every birthday, every diagnosis -- that changes the equation. The clients who are most grateful for their coverage are the ones who got it when they were healthy and then something unexpected happened."'},
    {q:'"What if I pay off the mortgage before the term ends?"',a:'"Great problem to have -- and most policies are structured to align with your mortgage term so you\'re not paying for coverage you no longer need. Some policies have a decreasing benefit that mirrors your remaining balance. We can structure it to fit your specific situation."'}
  ]},
  mp_close:{title:"Presentation and Closing Objections",sub:"Mortgage Protection -- Step 4",items:[
    {q:'"Why do you need my Social Security number?" / "I\'m not comfortable giving that out."',a:'"Understood, I hear ya (client\'s name). The insurance carrier requires that because that\'s how they\'re going to check your medical and prescription history, and it also prevents fraud so someone\'s not signing up for coverage in your name. Does that make sense? Okay cool -- confirm that social with me again?<br><br><em>If they give more pushback:</em> We actually have insurance that if anybody were able to get through all of our firewalls and access your info, it would cover you for up to a million dollars. That should be enough, right? <em>(wait for response)</em> Ok, go ahead with the social."'},
    {q:'"Why do you need my bank information?" / "I don\'t want to give that out."',a:'"The insurance carrier either requires a voided check or account number to verify there is no insurance fraud, money laundering, or anything else fraudulent linked to your account -- and of course that\'s also how you\'ll be paying for the policy once you\'re approved. Anyway, looks like the address we have on file to mail the policy out to is ___?<br><br><em>If they\'re still giving pushback:</em> I also just texted you a link to the Department of Insurance to look up my information and make sure I\'m legit. Let me know when you get the link. <em>(walk them through how to verify your license: https://sbs.naic.org/solar-external-lookup)</em>"'},
    {q:'"I just want to think about it."',a:'"Totally respect that. Is there something still unclear, or are you just needing a little time? What we can do is submit the application just to see what you qualify for -- no commitment, and you can still think it over while it\'s reviewed. That way you lock in your health rating now in case anything changes later."'},
    {q:'"Can you just send me something?"',a:'"Of course -- but these plans are tailored based on your age, health, and mortgage balance. If I just send something it\'s going to be generic and not even accurate. Would you prefer options with lower monthly payments or ones that pay the mortgage off in full? Let me get you real numbers based on your actual situation."'},
    {q:'"I want to compare other options."',a:'"That\'s smart -- and I\'ll save you the time. I\'m a broker. I represent multiple top-rated carriers. I already ran you through the field and these are the best options available in your state for your health profile and mortgage situation. You\'re already looking at a comparison. What specifically are you hoping to find somewhere else?"'},
    {q:'"The monthly payment is too high."',a:'"Let\'s figure out what does work. I showed you three options -- was there one closer to what you were thinking? Or is it the concept of adding a monthly payment that feels like too much right now? I can also look at a shorter term or a reduced benefit to bring the number down. What range were you thinking?"'},
    {q:'"My financial advisor told me to invest instead."',a:'"The two are not mutually exclusive. The question your advisor probably didn\'t address is: what protects the investment while you\'re building it? If something happened to you today, before the portfolio is large enough to absorb the mortgage, your family loses the home. This is not instead of investing -- it\'s what protects the plan while the plan is still being built."'},
    {q:'"Let me sleep on it."',a:'"Totally fair. What I recommend is that we submit the application to lock in your age and health now, and while it\'s in review you\'ve got time to decide. If you change your mind, no problem -- no payment required."'},
    {q:'"What if I pay into it and never use it?"',a:'"That\'s exactly why this is designed to protect your family during the years they\'d be most impacted -- while the mortgage is active. It\'s peace of mind knowing the home\'s protected while it\'s still a big liability."'},
    {q:'"I\'ll be okay -- my family can figure things out."',a:'"I respect that -- but can I be real with you for a second? Most families don\'t figure it out. Grieving plus mortgage payments is a heavy combination. Mortgage protection is about giving your loved ones the gift of time -- time to grieve, to adjust, and to stay in the home without scrambling."'},
    {q:'"I\'m still young -- I\'ve got time."',a:'"That\'s exactly why now is the smartest time. You qualify for the best rates and the most coverage while you\'re young and healthy. Waiting doesn\'t make it cheaper -- it only makes it riskier. This kind of coverage is like locking in your health today -- even if things change tomorrow."'},
    {q:'"Need to think about it / Talk to spouse."',a:'"Okay, sure -- do you need to think about whether or not you want the coverage at all, or do you know you want the coverage and it\'s just a matter of which option you want to pick?<br><br><em>If they want it:</em> Completely understandable ___(client\'s name)___. You want to know what I\'d recommend? Honestly, I\'d recommend starting out at the low end for what you know you can afford, because you\'re actually going to see me twice. Once now, but also a year from now -- I simply check in, re-explain the policy benefits, and if you want to bump up the coverage at that time you certainly have the option. Anyway, the address we have on file to mail the policy out to is ____ right?<br><br><em>If they still don\'t want it:</em> Go back into the why and dig into their pain points on why they need the coverage."'},
    {q:'"Do I have to make a decision today?"',a:'"Yes, I do need to submit that original coverage through today -- however, since most of us need time to look over our finances to see which option we want to go with, which is understandable, what I\'d recommend for your situation is simply starting out on the low end for what you know you can afford. If you want to bump up the coverage you can always give me a call or shoot me a text. I also do annual reviews with my clients so we will review this a year from now and you\'ll have the option to bump it up at that point as well. Anyway, the address we have on file to mail the policy out to is ____ right?"'},
    {q:'"We don\'t need mortgage protection -- our home is covered with our life insurance."',a:'"Gotcha -- has anyone explained the difference between mortgage protection and life insurance to you before? So mortgage protection and life insurance both pay out as a check directly to your beneficiary when you pass away. The reason that mortgage protection is a bit better is because mortgage protection covers you on the living side as well -- NOT JUST the death side. What that means is any situation where you get sick, disabled, cancer, heart attack, stroke, or any other sort of critical, chronic, or terminal illness this policy is paying out as well in order to supplement that loss of income and pay for any medical bills. I\'m not sure if you\'re aware of this ___(client\'s name)___ but the biggest cause of bankruptcies and home foreclosures is NOT due to a death -- it\'s either due to unforeseen medical bills, or being disabled for a period of time and not being able to work. That is why our clients love this coverage so much, because you have an 89% higher likelihood of becoming disabled or sick than you are of passing away. Does that make sense?"'},
    {q:'"Do you have anything cheaper?"',a:'"When you jump out of a plane do you want the cheapest parachute or the best parachute? If you just want cheap life insurance I can certainly help you with that -- but you mentioned the ___(cash value AND/OR living benefits)___ was important to you?"'}
  ]},
  mp_bank:{title:"Banking Objections",sub:"Mortgage Protection -- Step 5",items:[
    {q:'"Why do you need my bank information?" / "I don\'t want to give that out."',a:'"The insurance carrier either requires a voided check or account number to verify there is no insurance fraud, money laundering, or anything else fraudulent linked to your account -- and of course that\'s also how you\'ll be paying for the policy once you\'re approved. Anyway, looks like the address we have on file to mail the policy out to is ___?<br><br><em>If they\'re still giving pushback:</em> I also just texted you a link to the Department of Insurance to look up my information and make sure I\'m legit. Let me know when you get the link. <em>(walk them through how to verify your license: https://sbs.naic.org/solar-external-lookup)</em>"'},
    {q:'"What if I cancel -- will you keep charging me?"',a:'"No -- the moment you cancel, the draft stops. You\'ll receive written confirmation and the carrier is required to stop all future drafts. You also have a free look period after the policy is issued -- typically 10 to 30 days -- where you can cancel and get a full refund."'},
    {q:'"I don\'t have my checkbook."',a:'"No problem -- do you get your bank statement in the mail or email? That will have the same information. Or if you have your bank\'s mobile app, we can find the account and routing number in there. And if none of those work, we can use a debit card for now and update the bank information once the policy is issued."'}
  ]},

  mp_resist:{title:"Resistance Objections",sub:"Mortgage Protection -- Step 4",items:[
    {q:'"Is this required?"',a:'"Oooof… I mean… technically they won\'t take your home away if you don\'t... uh but I will tell you… you\'d be one of the rare people not to put it in place since it\'s just such crucial coverage… It\'d be like driving a car without car insurance, if that makes sense." <em>*(act confused and a bit thrown off guard as to why they would even ask that)*</em>'},
    {q:'"We don\'t need mortgage protection -- our home is covered with our life insurance."',a:'"Gotcha -- has anyone explained the difference between mortgage protection and life insurance to you before? So mortgage protection and life insurance both pay out as a check directly to your beneficiary when you pass away. The reason that mortgage protection is a bit better is because mortgage protection covers you on the living side as well -- NOT JUST the death side. What that means is any situation where you get sick, disabled, cancer, heart attack, stroke, or any other sort of critical, chronic, or terminal illness this policy is paying out as well in order to supplement that loss of income and pay for any medical bills. I\'m not sure if you\'re aware of this ___(client\'s name)___ but the biggest cause of bankruptcies and home foreclosures is NOT due to a death -- it\'s either due to unforeseen medical bills, or being disabled for a period of time and not being able to work. That is why our clients love this coverage so much, because you have an 89% higher likelihood of becoming disabled or sick than you are of passing away. Does that make sense?"'},
    {q:'"I\'ll be okay -- my family can figure things out."',a:'"I respect that -- but can I be real with you for a second? Most families don\'t figure it out. Grieving plus mortgage payments is a heavy combination. Mortgage protection is about giving your loved ones the gift of time -- time to grieve, to adjust, and to stay in the home without scrambling."'},
    {q:'"I\'m healthy -- I don\'t need to worry about this."',a:'"Being healthy is exactly why right now is the best time to lock this in. Rates are based on your health today. Every year that passes, every birthday, every diagnosis -- that changes the equation. The clients who are most grateful for their coverage are the ones who got it when they were healthy and then something unexpected happened."'},
    {q:'"I have enough savings to cover it."',a:'"That\'s great -- and I want to make sure the math holds. The average mortgage balance is over $200,000. If that came due because of an unexpected death or disability, would your savings absorb that and still leave your family financially stable? For most people, the savings are earmarked for other things."'},
    {q:'"What if I pay into it and never use it?"',a:'"That\'s exactly why this is designed to protect your family during the years they\'d be most impacted -- while the mortgage is active. It\'s peace of mind knowing the home\'s protected while it\'s still a big liability."'},
    {q:'"I\'m still young -- I\'ve got time."',a:'"That\'s exactly why now is the smartest time. You qualify for the best rates and the most coverage while you\'re young and healthy. Waiting doesn\'t make it cheaper -- it only makes it riskier. This kind of coverage is like locking in your health today -- even if things change tomorrow."'},
    {q:'"I\'m not interested."',a:'"Understandably, most people aren\'t interested until they get cancer, disabled, or God forbid pass away -- anyway it looks like the address we have on file for the home is ____?<br><br><em>2nd time:</em> Hmm, well I\'m assuming what was on your mind when you submitted this request to our office was simply providing some sort of practical, affordable coverage to protect the home and your family God forbid when something does happen to you…?<br><br><em>3rd time:</em> Ok, well are you afraid the price is going to be too high or are you afraid you\'re going to be declined?"'}
  ]},
  mp_app:{title:"Application Objections",sub:"Mortgage Protection -- Step 5",items:[
    {q:'"Why do you need my Social Security number?" / "I\'m not comfortable giving that out."',a:'"Understood, I hear ya (client\'s name). The insurance carrier requires that because that\'s how they\'re going to check your medical and prescription history, and it also prevents fraud so someone\'s not signing up for coverage in your name. Does that make sense? Okay cool -- confirm that social with me again?<br><br><em>If they give more pushback:</em> We actually have insurance that if anybody were able to get through all of our firewalls and access your info, it would cover you for up to a million dollars. That should be enough, right? <em>(wait for response)</em> Ok, go ahead with the social."'},
    {q:'"Why do you need my bank information?" / "I don\'t want to give that out."',a:'"The insurance carrier either requires a voided check or account number to verify there is no insurance fraud, money laundering, or anything else fraudulent linked to your account -- and of course that\'s also how you\'ll be paying for the policy once you\'re approved. Anyway, looks like the address we have on file to mail the policy out to is ___?<br><br><em>If they\'re still giving pushback:</em> I also just texted you a link to the Department of Insurance to look up my information and make sure I\'m legit. Let me know when you get the link. <em>(walk them through how to verify your license: https://sbs.naic.org/solar-external-lookup)</em>"'},
    {q:'"I just want to think about it."',a:'"Totally respect that. Is there something still unclear, or are you just needing a little time? What we can do is submit the application just to see what you qualify for -- no commitment, and you can still think it over while it\'s reviewed. That way you lock in your health rating now in case anything changes later."'},
    {q:'"Need to think about it / Talk to spouse."',a:'"Okay, sure -- do you need to think about whether or not you want the coverage at all, or do you know you want the coverage and it\'s just a matter of which option you want to pick?<br><br><em>If they want it:</em> Completely understandable ___(client\'s name)___. You want to know what I\'d recommend? Honestly, I\'d recommend starting out at the low end for what you know you can afford, because you\'re actually going to see me twice. Once now, but also a year from now -- I simply check in, re-explain the policy benefits, and if you want to bump up the coverage at that time you certainly have the option. Anyway, the address we have on file to mail the policy out to is ____ right?<br><br><em>If they still don\'t want it:</em> Go back into the why and dig into their pain points on why they need the coverage."'},
    {q:'"Let me sleep on it."',a:'"Totally fair. What I recommend is that we submit the application to lock in your age and health now, and while it\'s in review you\'ve got time to decide. If you change your mind, no problem -- no payment required."'},
    {q:'"Do I have to make a decision today?"',a:'"Yes, I do need to submit that original coverage through today -- however, since most of us need time to look over our finances to see which option we want to go with, what I\'d recommend is simply starting out on the low end for what you know you can afford. If you want to bump up the coverage you can always call or text me. I also do annual reviews so we\'ll revisit this in a year. Anyway, the address we have on file to mail the policy out to is ____ right?"'},
    {q:'"The monthly payment is too high."',a:'"Let\'s figure out what does work. I showed you three options -- was there one closer to what you were thinking? Or is it the concept of adding a monthly payment that feels like too much right now? I can also look at a shorter term or a reduced benefit to bring the number down. What range were you thinking?"'},
    {q:'"Do you have anything cheaper?"',a:'"When you jump out of a plane do you want the cheapest parachute or the best parachute? If you just want cheap life insurance I can certainly help you with that -- but you mentioned the ___(cash value AND/OR living benefits)___ was important to you?"'},
    {q:'"Can you just send me something?"',a:'"Of course -- but these plans are tailored based on your age, health, and mortgage balance. If I just send something it\'s going to be generic and not even accurate. Would you prefer options with lower monthly payments or ones that pay the mortgage off in full? Let me get you real numbers based on your actual situation."'},
    {q:'"What if I cancel -- will you keep charging me?"',a:'"No -- the moment you cancel, the draft stops. You\'ll receive written confirmation and the carrier is required to stop all future drafts. You also have a free look period after the policy is issued -- typically 10 to 30 days -- where you can cancel and get a full refund."'},
    {q:'"I don\'t have my checkbook."',a:'"No problem -- do you get your bank statement in the mail or email? That will have the same information. Or if you have your bank\'s mobile app, we can find the account and routing number in there. And if none of those work, we can use a debit card for now and update the bank information once the policy is issued."'}
  ]},
  iu_intro:{title:"IUL Intro Objections",sub:"IUL -- Step 1",items:[
    {q:'"I\'ve never heard of an IUL -- is this legit?"',a:'"100% -- Indexed Universal Life is one of the most powerful financial products in existence and has been around for decades. Walt Disney used it to fund Disneyland when the banks wouldn\'t give him a loan. It\'s a whole life insurance policy with a cash value component tied to a stock market index."'},
    {q:'"I already have a 401K -- why do I need this?"',a:'"Great question -- and the answer is taxes and control. Your 401K is tax-deferred, meaning you pay taxes when you take the money out at whatever rate applies then. An IUL grows tax-free and the money comes out tax-free. And unlike your 401K, you\'re not penalized for accessing it before 59 and a half. They\'re complementary strategies -- not competing ones."'},
    {q:'"Is this a whole life policy? I heard those are bad."',a:'"You\'ve probably heard that from people comparing whole life to term for pure death benefit -- and in that context, they\'re right. But an IUL is a different animal. It\'s designed specifically for people who want the life insurance benefit and the cash value growth. If you just want the cheapest death benefit, buy term. If you want a financial vehicle that builds wealth, protects your family, and gives you tax-free access -- that\'s what this is."'},
    {q:'"What if I need the money before I expected to?"',a:'"That\'s actually one of the features, not a bug. The cash value in an IUL is accessible at any time through a policy loan. No penalty, no tax, no questions from the IRS. You borrow against the death benefit, the cash value keeps growing as if you never touched it, and you pay it back on your own timeline."'}
  ]},
  iu_disc:{title:"Discovery Objections",sub:"IUL -- Step 2",items:[
    {q:'"I\'m not sure I need life insurance."',a:'"Let me ask you this -- if you passed away tomorrow, is there anyone whose life would be financially impacted? A spouse, kids, parents, a business partner? If the answer is yes, then the question is not whether you need it -- it\'s how much, what kind, and how to make it work the hardest for you."'},
    {q:'"I can\'t afford another monthly payment."',a:'"That\'s actually the conversation I want to have -- because I don\'t know yet what makes sense for your situation. Some clients put in $100 a month. Some put in $1,000. What I want to figure out is what amount, if you set it aside every month into something that builds compound interest and never goes down in a down market, would actually feel worth it to you."'},
    {q:'"My employer already has life insurance on me."',a:'"How much? And what happens to it if you change jobs or get laid off? Employer-provided life insurance is group coverage -- it\'s not yours, not permanent, and not portable. Most of those policies are term and they disappear the moment your employment ends. What I\'m talking about is something you own, forever, regardless of where you work."'},
    {q:'"I want to do my own research first."',a:'"Please do -- I actually encourage it. Look up Indexed Universal Life and how the S&P 500 floor works. Look up the carriers I mentioned. Verify my license. Then call me back and we can have an even better conversation. While you\'re researching, pay attention to the tax-free loan provision -- because that\'s the piece most financial articles miss."'}
  ]},
  iu_pres:{title:"IUL Presentation Objections",sub:"IUL -- Step 3",items:[
    {q:'"What if the stock market crashes?"',a:'"That\'s the best part -- and it\'s what makes an IUL different from everything else. Your index has a floor of zero. If the market goes down 30%, your cash value goes down zero. You simply don\'t participate in the loss. When the market recovers, you start earning again from wherever you left off."'},
    {q:'"How is this different from just investing in the S&P 500 directly?"',a:'"Three things. First -- the floor. In the S&P 500 directly, a down year means you lose money. In an IUL, a down year means you stay flat. Second -- taxes. Your S&P gains are taxed. Your IUL cash value grows tax-free and comes out tax-free. Third -- the death benefit. Your S&P account does not pay your family a lump sum if you die. Your IUL does."'},
    {q:'"What are the fees?"',a:'"There are internal costs of insurance -- the actual cost of the death benefit -- which is taken out of the premium. These are disclosed fully in the illustration I\'ll send you. Even accounting for those costs, the tax advantage and floor protection make the net return competitive over a long timeline."'},
    {q:'"What is the cap on growth?"',a:'"Most IUL policies have a participation rate and a cap -- typically between 10% and 14% depending on the carrier. The trade-off for the cap is the floor -- you never lose. Over a long timeline, that combination outperforms most taxable accounts because you\'re never starting from a loss."'}
  ]},
  iu_quote:{title:"Quoting and Premium Objections",sub:"IUL -- Step 4",items:[
    {q:'"The quote seems high."',a:'"Let me reframe that. You\'re not spending money -- you\'re moving money into an asset that builds compound interest, protects your family, and gives you tax-free access. What would you normally do with that money each month? Leave it in a checking account earning near-zero interest? This is the same money doing a completely different job."'},
    {q:'"I want to think about it before I pick an amount."',a:'"Totally fair -- and here\'s a thought. We can start you at the minimum just to see what you qualify for and lock in your health rating today. You can always adjust the amount once you see the full illustration. There\'s no right or wrong answer -- it\'s just about getting you into the right structure. What would feel like a comfortable starting point?"'},
    {q:'"How does the loan actually work -- won\'t I owe interest?"',a:'"Great question. When you take a policy loan, you\'re borrowing against your death benefit -- not from the cash value itself. The cash value stays in the index earning compound interest the whole time. The loan does accrue a small interest charge, but in most cases the growth in the index more than offsets it. And there are no required repayment terms -- you pay it back on your own schedule or it reduces the death benefit."'}
  ]},
  iu_close:{title:"Closing Objections",sub:"IUL -- Step 5",items:[
    {q:'"I want to talk to my financial advisor first."',a:'"Absolutely -- and I respect that. One thing to flag when you have that conversation: most financial advisors are either fee-based or securities-licensed. They\'re incentivized to direct you toward products they manage. Ask them specifically about the tax-free loan provision of an IUL and watch the reaction. If they\'re familiar with it, great. If they dismiss it without explaining it -- that tells you something."'},
    {q:'"What if the carrier goes out of business?"',a:'"Life insurance companies are regulated at the state level and most states have guarantee associations that protect policyholders even if the carrier fails. We also only work with A-rated carriers -- companies that have been around 50 to 100 years and have the reserves to back every policy they\'ve ever written."'},
    {q:'"I\'m too young to worry about this."',a:'"You\'re actually exactly the right age -- and that\'s not a sales line, it\'s math. The younger and healthier you are when you lock in a permanent policy, the lower your cost of insurance inside the policy, and the more of your premium goes into cash value. Every year you wait costs you in three ways: higher rates, less time to compound, and the risk that your health changes."'},
    {q:'"I\'ll just invest the money myself."',a:'"I love that instinct -- and if you\'ll actually do it consistently, every month without exception, never touch it, and not mind paying taxes on the gains, then yes, direct investing can work. But here\'s the honest question: what percentage of people actually do that with discipline over 20 or 30 years? And what happens to your plan if you get sick, disabled, or die before the account is large enough to replace your income? This is the piece self-directed investing can\'t answer."'}
  ]},
  fia_open:{title:"FIA -- Opener Objections",sub:"Fixed Indexed Annuity -- Call 1, Step 1",items:[
    {q:'"I\'ve never heard of a Fixed Indexed Annuity."',a:'"That\'s completely normal -- FIAs are underutilized and underexplained. Let me give you the one-sentence version: your money grows when the market goes up, up to a cap, and earns zero when the market goes down. Your principal is guaranteed. That\'s the core promise."'},
    {q:'"I don\'t want to talk about my finances."',a:'"I completely respect that -- and I\'m not here to pry. All I need is a rough sense of the ballpark so I can tell you honestly whether what I do is even relevant for your situation. If it\'s not a fit, I\'ll tell you. Fair?"'},
    {q:'"I already have a financial advisor."',a:'"That\'s great -- and I\'m not here to replace anyone. What I specialize in specifically is the protection side of retirement money -- making sure a portion of your savings literally cannot go down. A lot of advisors don\'t offer FIAs because they\'re not securities products. It\'s worth knowing your options."'}
  ]},
  fia_funds:{title:"FIA -- Funds Discovery Objections",sub:"Fixed Indexed Annuity -- Call 1, Step 2",items:[
    {q:'"I don\'t want to tell you how much I have."',a:'"Totally fair -- even a range helps me. I\'m not asking for account numbers or anything sensitive. Just a rough ballpark so I can make sure the product I show you on our second call actually makes sense for your situation. Would you say it\'s under $100k, somewhere in between, or over $250k?"'},
    {q:'"It\'s in my 401k and I can\'t touch it."',a:'"If it\'s with a current employer and you\'re still actively contributing -- you\'re right, we can\'t move it. But if it\'s from a previous employer, or you\'re no longer actively contributing and receiving a match, a rollover is completely available to you with zero tax consequences if done correctly. Which situation are you in?"'},
    {q:'"My money is doing fine where it is."',a:'"That\'s great to hear -- and I\'m not here to tell you to move everything. The question I always ask is: what happens to \'doing fine\' if the market drops 30% next year? For money you\'re planning to retire on, \'fine\' isn\'t the same as \'protected.\' That\'s the conversation worth having."'}
  ]},
  fia_pain:{title:"FIA -- Pain Discovery Objections",sub:"Fixed Indexed Annuity -- Call 1, Step 3",items:[
    {q:'"The market has been great -- why would I change anything?"',a:'"The market has been great -- and that\'s exactly when people feel the least urgency to protect themselves. The best time to put a seatbelt on is before the crash, not during. For retirement money specifically, a 30% loss the year before you retire isn\'t something you get to wait out. It changes your life. That\'s the risk we\'re talking about eliminating."'},
    {q:'"I\'m not worried about losing money."',a:'"I respect that confidence. Can I ask -- have you experienced a significant market drop with this money before? Because most people who\'ve lived through 2008 or 2020 with real retirement money say the same thing beforehand. The goal isn\'t to scare you -- it\'s to make sure the money you\'ve spent decades building is never at risk of a catastrophic setback."'}
  ]},
  fia_concept:{title:"FIA -- Product Understanding Objections",sub:"Fixed Indexed Annuity -- Call 1, Step 4",items:[
    {q:'"What\'s the catch?"',a:'"Great question -- and I\'d rather you ask it than wonder. The catch is the cap. Because the insurance company is guaranteeing you can never lose money, they put a ceiling on how much you can gain in any given year. You give up some upside in exchange for absolute downside protection. For most people protecting retirement savings, that\'s not a hard trade to make."'},
    {q:'"So my money isn\'t actually in the market?"',a:'"Correct -- and this trips a lot of people up. Your money is held by the insurance company in their general account, invested in bonds and stable assets. The index is just the measuring stick for how your growth gets calculated. You get the upside of index performance up to the cap, and a guaranteed floor of zero on the downside. You\'re participating in the market\'s gains without being exposed to its losses."'},
    {q:'"I don\'t fully understand how this works."',a:'"That\'s completely fair -- and honestly, most people don\'t until someone explains it right. One sentence: your money grows when the market goes up, up to a cap, and earns zero when the market goes down. Your principal never decreases. That\'s it. Everything else -- crediting methods, riders, participation rates -- those are just the mechanics underneath that one core promise."'},
    {q:'"What\'s a cap rate -- and what if the cap changes?"',a:'"The cap rate is the maximum you can earn in a given crediting period. Now here\'s the honest answer -- cap rates can change at renewal, typically annually or at the end of your term. Carriers adjust them based on interest rates and bond yields. What I can tell you is that even at a lower cap, the floor guarantee still holds. Your worst year is always zero. That doesn\'t change."'}
  ]},
  fia_appt:{title:"FIA -- Appointment Setting Objections",sub:"Fixed Indexed Annuity -- Call 1, Step 5",items:[
    {q:'"I need to think about it before a second call."',a:'"Totally respect that. What specifically are you wanting to think through? Because if it\'s a question I haven\'t answered, I\'d rather handle it now. And if you just want a few days to sit with it -- no problem. I\'ll send you over a quick one-pager on how FIAs work and we can schedule the numbers call for next week. What day works better for you?"'},
    {q:'"My spouse needs to be involved."',a:'"Perfect -- that\'s exactly what I was going to suggest. This affects both of you and I want both of you comfortable. Let\'s get them on the second call. When is a time that works for both of you together?"'}
  ]},
  fia_edu:{title:"FIA -- Education Phase Objections",sub:"Fixed Indexed Annuity -- Call 2, Step 6",items:[
    {q:'"The market has been doing great -- why would I cap my upside?"',a:'"That\'s exactly the right question to ask in a bull market. Here\'s the honest answer: if the market keeps going up forever with no corrections, yes -- you\'d do better fully invested. But history says that\'s not how it works. 2008 was down 38%. 2022 was down 19%. COVID dropped 34% in a month. When those years hit -- and they will again -- the person in an FIA earned zero. The person fully in the market potentially needed years to recover. For retirement money you can\'t afford to rebuild, the cap is cheap insurance."'},
    {q:'"I can get a better return in stocks."',a:'"You might. Over time, uncapped market exposure can outperform. But can you guarantee it? Can you guarantee you won\'t experience a 30% drop the year before you need to retire? The FIA isn\'t competing with your aggressive growth accounts -- it\'s competing with the risk of catastrophic loss on money you can\'t replace. Think of it as the foundation of your retirement -- the part that never breaks no matter what."'},
    {q:'"A CD or money market is simpler."',a:'"Simpler, yes. But a CD gives you a fixed rate that resets at term end, and you pay taxes on the interest every single year. An FIA has the potential to earn double digits in strong market years, growth is tax-deferred, and the floor protects you from loss. Over a 7-10 year period, the tax deferral and upside participation historically leave you ahead of a CD -- without any principal risk."'},
    {q:'"My financial advisor said annuities are bad."',a:'"I hear that a lot. Most legitimate criticism of annuities is aimed at variable annuities -- products that ARE in the market, charge 2-3% in annual fees, and can lose value. A Fixed Indexed Annuity is fundamentally different: no market exposure, no internal investment fees, and a 0% floor guarantee. Ask your advisor specifically what their objection is to a product that cannot lose principal. That\'s a different conversation."'}
  ]},
  fia_pres:{title:"FIA -- Presentation Objections",sub:"Fixed Indexed Annuity -- Call 2, Step 7",items:[
    {q:'"I\'ve never heard of that company."',a:'"That\'s common in this space -- annuity carriers aren\'t household names, but that\'s typical. What matters is their financial strength rating -- they\'re A-rated by AM Best, the independent gold standard for insurance company stability. Annuities are also protected under the state guaranty association up to $250,000 per contract holder."'},
    {q:'"What happens if the insurance company goes under?"',a:'"Insurance companies are regulated at the state level and required to hold reserves to cover their policy obligations. In the extremely rare case of insolvency, the state guaranty association covers annuity contracts -- similar to how the FDIC covers bank deposits. That protection is typically up to $250,000 per contract."'}
  ]},
  fia_close:{title:"FIA -- Closing Objections",sub:"Fixed Indexed Annuity -- Call 2, Step 8",items:[
    {q:'"What if I need the money?"',a:'"Built right into the contract is a free withdrawal provision -- you can access up to 10% of your account value every year without any surrender charge. Most carriers also waive surrender charges entirely for hospitalization, nursing home confinement, or terminal illness. So you\'re not locked out of your money -- you just have a structure around the bulk of it."'},
    {q:'"I don\'t want to be locked in for 7 or 10 years."',a:'"Think about what \'locked in\' actually means here: your money is growing, protected, and you have 10% annual access. The surrender period exists because the insurance company needs time to generate the returns that fund your cap and floor guarantees. The question is: do you realistically need more than 10% of this money in any given year? If the answer is no, the surrender period isn\'t really a constraint."'},
    {q:'"What are the fees on this?"',a:'"The base FIA has no explicit annual fee -- you\'re not paying a management fee or expense ratio the way you would in a mutual fund or variable annuity. The cost of the product is built into the cap rate. If there\'s an income rider, it does carry a fee -- typically around [Rider Fee]% annually. For most clients, the income that rider generates far exceeds that cost over the life of the contract."'},
    {q:'"I need to talk to my spouse first."',a:'"Of course -- and I\'d want them involved. Let\'s get them on a call together. This affects both of you and I want both of you confident in the decision. When\'s a time that works for both of you?"'},
    {q:'"I need to think about it."',a:'"Totally fair -- this is a big decision. Can I ask what specifically you want to think through? Because if there\'s a question I haven\'t answered, I want to make sure you have everything before we hang up. What would need to be true for you to feel ready to move forward?"'},
    {q:'"I want to wait and see what the market does."',a:'"Here\'s the thing about that -- the whole point of this product is that it doesn\'t matter what the market does. If it goes up, you earn up to [Cap Rate]. If it goes down, you earn zero. Waiting to see what the market does before you protect yourself from the market is like waiting to see if it rains before you buy an umbrella. The protection starts the day the contract is in force."'},
    {q:'"Won\'t I owe taxes when I move the money?"',a:'"Not if we do it the right way -- and that\'s our job to make sure it\'s done right. A direct rollover from your [Source of Funds] into an IRA-held annuity is a non-taxable transfer. The IRS doesn\'t treat it as a distribution. No taxes, no penalties, no withholding. It goes from one institution to another without you ever touching it."'},
    {q:'"My kids think I should just keep it in the market."',a:'"Your kids want you to grow your money -- that\'s great. But they\'re not retiring on this money. You are. The risk tolerance for someone in their 30s is completely different from someone protecting their retirement nest egg. Ask them this: what\'s the plan if the market drops 30% the year before you retire? A Fixed Indexed Annuity means that question is never on the table."'},
    {q:'"My financial advisor said annuities are bad."',a:'"Most criticism is aimed at variable annuities -- products that are in the market with high fees that can lose value. An FIA is fundamentally different: no market exposure, no internal investment fees, and a 0% floor. Ask your advisor specifically what their objection is to a product that cannot lose principal. That\'s a different conversation entirely."'}
  ]},
};
